/** **************************************************************************

\file

\brief Module stdio - standard I/O header

Copyright 2007 (C) S. A. Moore

Description

Defines the serial I/O platform for whitebook C. This is the interface header
for the stdio module; it declares the FILE structure, the standard streams, the
buffering and end of file flag definitions, and the full set of stdio calls.

Exports

The complete public interface of the stdio module, including the FILE type, the
stdin, stdout and stderr streams, and all of the stdio functions. See stdio.c
for the implementation and the per function descriptions.

******************************************************************************/

#ifndef _STDIO_H_
#define _STDIO_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdarg.h>

/*
 * This block of defines will "coin" all of the plain labeled stdio calls and
 * make them stdio_ coined names. This allows the stio calls to exist in 
 * parallel with the built-in stio package.
 *
 * Some systems don't need this (Windows, Mac OS X) because they can override
 * at link time.
 */

/*
 * Format checking: the attribute rides the prototypes below, and through
 * the function-like macros it lands on the stdio_ names, so gcc's
 * -Wformat polices every call in the tree. Empty where the compiler
 * has no such attribute.
 */
#if defined(__GNUC__) || defined(__clang__)
#define __stdio_format(kind, fi, va) __attribute__((format(kind, fi, va)))
#else
#define __stdio_format(kind, fi, va)
#endif

#ifdef STDIO_BYPASS

/*
 * Functions
 *
 * These are function-like macros so bare identifiers (format-attribute
 * arguments like `__attribute__((format(printf, 2, 3)))` in third-party
 * headers, address-of expressions, etc.) are left alone — only actual
 * `name(...)` calls get rewritten to `stdio_name(...)`.
 */
#define fopen(...)    stdio_fopen(__VA_ARGS__)
#define freopen(...)  stdio_freopen(__VA_ARGS__)
#define fdopen(...)   stdio_fdopen(__VA_ARGS__)
#define fflush(...)   stdio_fflush(__VA_ARGS__)
#define fclose(...)   stdio_fclose(__VA_ARGS__)
#define remove(...)   stdio_remove(__VA_ARGS__)
#define rename(...)   stdio_rename(__VA_ARGS__)
#define tmpfile(...)  stdio_tmpfile(__VA_ARGS__)
#define tmpnam(...)   stdio_tmpnam(__VA_ARGS__)
#define setvbuf(...)  stdio_setvbuf(__VA_ARGS__)
#define setbuf(...)   stdio_setbuf(__VA_ARGS__)
#define fprintf(...)  stdio_fprintf(__VA_ARGS__)
#define printf(...)   stdio_printf(__VA_ARGS__)
#define sprintf(...)  stdio_sprintf(__VA_ARGS__)
#define vprintf(...)  stdio_vprintf(__VA_ARGS__)
#define vfprintf(...) stdio_vfprintf(__VA_ARGS__)
#define vsprintf(...) stdio_vsprintf(__VA_ARGS__)
#define snprintf(...) stdio_snprintf(__VA_ARGS__)
#define vsnprintf(...) stdio_vsnprintf(__VA_ARGS__)
#define fscanf(...)   stdio_fscanf(__VA_ARGS__)
#define scanf(...)    stdio_scanf(__VA_ARGS__)
#define sscanf(...)   stdio_sscanf(__VA_ARGS__)
#define vscanf(...)   stdio_vscanf(__VA_ARGS__)
#define vfscanf(...)  stdio_vfscanf(__VA_ARGS__)
#define vsscanf(...)  stdio_vsscanf(__VA_ARGS__)
#define fgetc(...)    stdio_fgetc(__VA_ARGS__)
#define getc(...)     stdio_getc(__VA_ARGS__)
#define fgets(...)    stdio_fgets(__VA_ARGS__)
#define fputc(...)    stdio_fputc(__VA_ARGS__)
#define fputs(...)    stdio_fputs(__VA_ARGS__)
#define putc(...)     stdio_putc(__VA_ARGS__)
#define getchar(...)  stdio_getchar(__VA_ARGS__)
#define gets(...)     stdio_gets(__VA_ARGS__)
#define putchar(...)  stdio_putchar(__VA_ARGS__)
#define puts(...)     stdio_puts(__VA_ARGS__)
#define ungetc(...)   stdio_ungetc(__VA_ARGS__)
#define fread(...)    stdio_fread(__VA_ARGS__)
#define fwrite(...)   stdio_fwrite(__VA_ARGS__)
#define fseek(...)    stdio_fseek(__VA_ARGS__)
#define ftell(...)    stdio_ftell(__VA_ARGS__)
#define rewind(...)   stdio_rewind(__VA_ARGS__)
#define fgetpos(...)  stdio_fgetpos(__VA_ARGS__)
#define fsetpos(...)  stdio_fsetpos(__VA_ARGS__)
#define clearerr(...) stdio_clearerr(__VA_ARGS__)
#define feof(...)     stdio_feof(__VA_ARGS__)
#define ferror(...)   stdio_ferror(__VA_ARGS__)
#define perror(...)   stdio_perror(__VA_ARGS__)
#define fileno(...)   stdio_fileno(__VA_ARGS__)

/*
 * Type and global object-like renames (cannot be function-like since
 * they are not invoked).
 */
#define FILE        STDIO_FILE
#define stdin       stdio_stdin
#define stdout      stdio_stdout
#define stderr      stdio_err

#endif

/* enable this next define for testing mode */

/* Maximum length of a temporary file name from tmpnam(). Large enough to hold
   the temp directory path plus the unique component generated by tmpnam(). */
#define L_tmpnam 64
/* Number of unique temporary names tmpnam()/tmpfile() will generate. */
#define TMP_MAX 10000
/* Default temporary file directory, used when no temp environment variable is
   set. Overridden at runtime by TMPDIR, TEMP or TMP. */
#ifndef P_tmpdir
#define P_tmpdir "/tmp"
#endif
#define FOPEN_MAX 100

#define EOF (-1)

/* buffering modes */

#define _IOFBF 1 /* full buffering */
#define _IOLBF 2 /* line buffering */
#define _IONBF 3 /* no buffering */

#define BUFSIZ 512 /* standard buffer size */

/* where an fseek() is measured from. These belong to stdio.h by the C
   standard, and fseek() is declared below, so a program that includes
   this header and no other has to have them from here. */

#define SEEK_SET 0 /* from the start of the file */
#define SEEK_CUR 1 /* from where it is now */
#define SEEK_END 2 /* from the end of the file */

/* this switch allows getc() and putc() to be macros. This is the way LIBC does
   it, and the ability is included here for possible compatability issues */
//#define USEMACRO 1 /* use macros for getc and putc */

typedef long fpos_t;

/* Stream state and mode flags. These match the GNU libc _IO_FILE flag bits, so
   that "backdoor" accessors (freadahead, __fpending, freadable, fwritable,
   fseterr and friends) that read the FILE structure directly see the values
   they expect. */

#define _IO_MAGIC             0xFBAD0000 /* magic in the high word of _flags */
#define _IO_USER_BUF          0x0001 /* buffer was provided by the user */
#define _IO_UNBUFFERED        0x0002 /* stream is unbuffered */
#define _IO_NO_READS          0x0004 /* stream cannot be read */
#define _IO_NO_WRITES         0x0008 /* stream cannot be written */
#define _IO_EOF_SEEN          0x0010 /* end of file has been seen */
#define _IO_ERR_SEEN          0x0020 /* an I/O error has occurred */
#define _IO_LINKED            0x0080 /* stream is on the open chain */
#define _IO_IN_BACKUP         0x0100 /* reading from the backup (pushback) area */
#define _IO_LINE_BUF          0x0200 /* stream is line buffered */
#define _IO_CURRENTLY_PUTTING 0x0800 /* buffer currently holds pending writes */
#define _IO_IS_APPENDING      0x1000 /* stream is in append mode */
#define _IO_IS_FILEBUF        0x2000 /* stream is backed by a file */

/* compatibility names for the petit_ami end of file and error bits */
#define _EFEOF _IO_EOF_SEEN
#define _EFERR _IO_ERR_SEEN

/* standard file descriptor. The leading fields follow the GNU libc _IO_FILE
   layout (field names and order) so that code which reaches into the structure
   directly finds what it expects. The petit_ami specific fields are appended at
   the end. */

typedef struct _stdio_file {

    int   _flags;          /* status and mode flags, see _IO_* above */

    char *_IO_read_ptr;    /* current position in the get area */
    char *_IO_read_end;    /* end of valid read data in the get area */
    char *_IO_read_base;   /* start of the get / putback area */
    char *_IO_write_base;  /* start of pending write data */
    char *_IO_write_ptr;   /* current position in the put area */
    char *_IO_write_end;   /* end of the put area */
    char *_IO_buf_base;    /* start of the reserve (buffer) area */
    char *_IO_buf_end;     /* end of the reserve (buffer) area */
    char *_IO_save_base;   /* start of a saved get area (backup) */
    char *_IO_backup_base; /* first valid character of the backup area */
    char *_IO_save_end;    /* end of a saved get area (backup) */

    void *_markers;        /* unused, present for layout compatibility */
    struct _stdio_file *_chain; /* unused, present for layout compatibility */

    int   _fileno;         /* underlying file descriptor, <0 if unused */
    int   _flags2;         /* secondary flags, unused */
    long  _old_offset;     /* legacy offset, unused */

    unsigned short _cur_column; /* unused */
    signed char    _vtable_offset; /* unused */
    char  _shortbuf[1];    /* one byte buffer for unbuffered pushback */

    void *_lock;           /* unused */
    long  _offset;         /* file offset for large file support, unused */

    /* petit_ami specific fields, appended after the glibc layout */

    char *name;            /* file name for error and diagnostics */
    int   text;            /* text/binary mode flag */

} FILE;

/* standard in, out and error files */

extern FILE* stdin;
extern FILE* stdout;
extern FILE* stderr;

FILE *fopen(const char* filename, const char* mode);
FILE *freopen(const char* filename, const char* mode, FILE* stream);
FILE *fdopen(int fd, const char *mode);
int fflush(FILE* stream);
int fclose(FILE* stream);
int remove(const char *filename);
int rename(const char *oldname, const char *newname);
FILE *tmpfile(void);
char *tmpnam(char s[]);
int setvbuf(FILE* stream, char *buf, int mode, size_t size);
void setbuf(FILE* stream, char *buf);
int fprintf(FILE* stream, const char *format, ...) __stdio_format(printf, 2, 3);
int printf(const char* format, ...) __stdio_format(printf, 1, 2);
int sprintf(char* s, const char *format, ...) __stdio_format(printf, 2, 3);
int snprintf(char* s, size_t n, const char *format, ...) __stdio_format(printf, 3, 4);
int vprintf(const char* format, va_list arg) __stdio_format(printf, 1, 0);
int vfprintf(FILE* stream, const char *format, va_list arg) __stdio_format(printf, 2, 0);
int vsprintf(char* s, const char *format, va_list arg) __stdio_format(printf, 2, 0);
int vsnprintf(char* s, size_t n, const char *format, va_list arg) __stdio_format(printf, 3, 0);
int fscanf(FILE* stream, const char *format, ...) __stdio_format(scanf, 2, 3);
int scanf(const char* format, ...) __stdio_format(scanf, 1, 2);
int sscanf(const char* s, const char *format, ...) __stdio_format(scanf, 2, 3);
int vscanf(const char *format, va_list arg) __stdio_format(scanf, 1, 0);
int vfscanf(FILE* stream, const char *format, va_list arg) __stdio_format(scanf, 2, 0);
int vsscanf(const char* s, const char *format, va_list arg) __stdio_format(scanf, 2, 0);
int fgetc(FILE *stream);
char *fgets(char *s, int n, FILE *stream);
int fputc(int c, FILE *stream);
int fputs(const char *s, FILE *stream);
int getc(FILE *stream);
int getchar(void);
char *gets(char *s);
int putc(int c, FILE *stream);
int putchar(int c);
int puts(const char *s);
int ungetc(int c, FILE *stream);
size_t fread(void *ptr, size_t size, size_t nobj, FILE *stream);
size_t fwrite(const void *ptr, size_t size, size_t nobj, FILE *stream);
int fseek(FILE* stream, long offset, int origin);
long ftell(FILE* stream);
void rewind(FILE* stream);
int fgetpos(FILE* stream, fpos_t *ptr);
int fsetpos(FILE* stream, const fpos_t *ptr);
void clearerr(FILE* stream);
int feof(FILE* stream);
int ferror(FILE* stream);
void perror(const char *s);
int fileno(FILE* stream);

#ifdef __cplusplus
}
#endif

#endif /* stdio.h */
